image: node:6.10.0

variables:
  BINTRAY_STAGING: 'https://staging-packages.unity.com'

before_script:
  - chmod +x build.sh

stages:
  - push_to_packman_staging

push_to_packman_staging:
  stage: push_to_packman_staging
  only:
    - tags
  script:
    - ./build.sh npm auth "$BINTRAY_STAGING" "$USER_NAME" "$API_KEY"
    - ./build.sh package-ci publish --git-head $CI_COMMIT_SHA --git-url $CI_REPOSITORY_URL
